<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.3.0/milligram.css" type="text/css" >
    </head>
    <body>
        
        <img src="https://pruebas-daw-martinhda.c9users.io/labService/templates/ciclo.JPG"></img>
            <p>Prueba hacer <a href="http://www.cocinadelirante.com/guarnicion/elotes-de-sabores">click para cocinar tu elote </a></p>
        <table>
            <tr>
                <th>
                    Estado
                </th>
                <th>
                    Sabor
                </th>
                <th>
                    Consistencia
                </th>
            </tr>
            <tr>
                <td>Mazorca</td><td>Maíz</td><td>Duro</td>
            </tr>
            <tr>
                <td>Elote</td><td>Salado, dependiendo de lo que le pongas</td><td>Sólido</td>
            </tr>
            <tr>
                <td>Tortilla</td><td>Sabor salado, recomendado cunado está recién hecho</td><td>Sólido y suave</td>
            </tr>
            <tr>
                <td>Atole</td><td>Dulce, de varios sabores</td><td>Suave, líquido</td>
            </tr>
        </table>
    </body>
</html>
