<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.3.0/milligram.css" type="text/css">
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
        <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
        <link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
    </head>
    <body>
        <h1>PANQUEQUES</h1>
        <div>Hechos de elote</div>

       <img src="https://pruebas-daw-martinhda.c9users.io/labService/templates/panqueque.jpg"></img>
       
       <p>
    El elote fresco funciona muy bien en esta receta.  Cocine 2 mazorcas grandes por 5 minutos en agua hirviente y luego enfríe en agua muy fría.  Corte los granos de la mazorca, estilo crema de elote (corte los granos con un corte poco profundo luego rasque la mazorca para quitar el resto del grano). Añada a la masa.
    Sirve los panqueques con salsa o con puré de manzana.
    Esta receta también se puede preparar con su mezcla favorita para panqueques. Prepare suficiente mezcla para seis porciones. Luego, añada 1 lata de elote enlatado o 2 tazas de elote fresco, cocido y cortado de la mazorca.
       </p>
    </body>
</html>
